# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
import json

import serial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItem
from PyQt5.QtWidgets import QHeaderView


class Ui_MainWindow(object):
    listme = []
    ser = serial.Serial()
    stop = -1
    stopchange = -1
    getfirst = 0
    js = json.load(open('./limit.json'))
    Tranl = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 664)
        MainWindow.setMinimumSize(QtCore.QSize(873, 664))
        MainWindow.setMaximumSize(QtCore.QSize(873, 664))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/bitbug_favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 281, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ico/advertisement.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 61, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/ico/easyicon.net.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 61, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/ico/display_128px_32208_easyicon.net.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.hide()
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 30, 54, 12))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(450, 0, 411, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/connection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setCheckable(False)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_2.setCheckable(False)
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(False)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/config_configuration_256px_1132478_easyicon.net.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_3.setCheckable(False)
        self.toolButton_3.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(False)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/slide_show_200px_1189770_easyicon.net.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_4.setCheckable(False)
        self.toolButton_4.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setAutoRaise(False)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/about_256px_1074528_easyicon.net.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_5.setCheckable(False)
        self.toolButton_5.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setAutoRaise(False)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/language_32px_1103239_easyicon.net.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon6)
        self.toolButton_6.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_6.setCheckable(False)
        self.toolButton_6.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setAutoRaise(False)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout.addWidget(self.toolButton_6)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(0, 70, 870, 590))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.widget1)
        self.tableView.setMinimumSize(QtCore.QSize(431, 291))
        self.tableView.setMaximumSize(QtCore.QSize(431, 291))
        self.tableView.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.widget1)
        self.tableView_2.setMinimumSize(QtCore.QSize(431, 291))
        self.tableView_2.setMaximumSize(QtCore.QSize(431, 291))
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout.addWidget(self.tableView_2, 0, 1, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(self.widget1)
        self.tableView_3.setMinimumSize(QtCore.QSize(431, 291))
        self.tableView_3.setMaximumSize(QtCore.QSize(431, 291))
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout.addWidget(self.tableView_3, 1, 0, 1, 1)
        self.tableView_4 = QtWidgets.QTableView(self.widget1)
        self.tableView_4.setMinimumSize(QtCore.QSize(431, 291))
        self.tableView_4.setMaximumSize(QtCore.QSize(431, 291))
        self.tableView_4.setObjectName("tableView_4")
        self.gridLayout.addWidget(self.tableView_4, 1, 1, 1, 1)
        self.model = QtGui.QStandardItemModel(self.tableView)
        self.model.setRowCount(10)
        self.model.setColumnCount(3)
        self.model.setHeaderData(0, QtCore.Qt.Horizontal, "序号(No)")
        self.model.setHeaderData(1, QtCore.Qt.Horizontal, "参数描述 (电机参数)")
        self.model.setHeaderData(2, QtCore.Qt.Horizontal, "数值(Value)")
        self.model2 = QtGui.QStandardItemModel(self.tableView_2)
        self.model2.setRowCount(10)
        self.model2.setColumnCount(3)
        self.model2.setHeaderData(0, QtCore.Qt.Horizontal, "序号(No)")
        self.model2.setHeaderData(1, QtCore.Qt.Horizontal, "参数描述 (控制参数一)")
        self.model2.setHeaderData(2, QtCore.Qt.Horizontal, "数值(Value)")
        self.model3 = QtGui.QStandardItemModel(self.tableView_3)
        self.model3.setRowCount(10)
        self.model3.setColumnCount(3)
        self.model3.setHeaderData(0, QtCore.Qt.Horizontal, "序号(No)")
        self.model3.setHeaderData(1, QtCore.Qt.Horizontal, "参数描述 (控制参数二)")
        self.model3.setHeaderData(2, QtCore.Qt.Horizontal, "数值(Value)")
        self.model4 = QtGui.QStandardItemModel(self.tableView_4)
        self.model4.setRowCount(9)
        self.model4.setColumnCount(3)
        self.model4.setHeaderData(0, QtCore.Qt.Horizontal, "序号(No)")
        self.model4.setHeaderData(1, QtCore.Qt.Horizontal, "参数描述 (实时状态)")
        self.model4.setHeaderData(2, QtCore.Qt.Horizontal, "数值(Value)")
        self.tableView.setModel(self.model)
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView_2.setModel(self.model2)
        self.tableView_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView_2.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.tableView_2.verticalHeader().setVisible(False)
        self.tableView_3.setModel(self.model3)
        self.tableView_3.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView_3.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.tableView_3.verticalHeader().setVisible(False)
        self.tableView_4.setModel(self.model4)
        self.tableView_4.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView_4.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.tableView_4.verticalHeader().setVisible(False)
        for number in range(0, 18):
            self.model.setItem(number, 0, QStandardItem('S' + str(number)))
        self.model.setItem(0, 1, QStandardItem('电机类型(0~3)'))
        self.model.setItem(1, 1, QStandardItem('电机额定功率(0~150.0KW)'))
        self.model.setItem(2, 1, QStandardItem('电机额定电压(0~400.0V)'))
        self.model.setItem(3, 1, QStandardItem('电机额定电流(10.0~600.0A)'))
        self.model.setItem(4, 1, QStandardItem('电机额定频率(10.0~300.0Hz)'))
        self.model.setItem(5, 1, QStandardItem('电机最大频率(10.0~400.0Hz)'))
        self.model.setItem(6, 1, QStandardItem('电机额定转速(100~6000rpm)'))
        self.model.setItem(7, 1, QStandardItem('最高转速限定(0~9000rpm)'))
        self.model.setItem(8, 1, QStandardItem('异步电机空载电流(15~45%电机额定电流)'))
        self.model.setItem(9, 1, QStandardItem('转子时间常数(0~10000)'))
        self.model.setItem(10, 1, QStandardItem('空载电流提升(0~50%电机额定电流)'))
        self.model.setItem(11, 1, QStandardItem('空载电流切换频率(1~50%电机额定频率)'))
        self.model.setItem(12, 1, QStandardItem('编码器每圈脉冲数(1~10000)'))
        self.model.setItem(13, 1, QStandardItem('编码器方向(0~1)'))
        self.model.setItem(14, 1, QStandardItem('同步电机磁极初始角度(0~360.0度)'))
        self.model.setItem(15, 1, QStandardItem('运行方向指示(0~3)'))
        self.model.setItem(16, 1, QStandardItem('保留1(0~32767)'))
        self.model.setItem(17, 1, QStandardItem('保留2(0~32767)'))
        for number in range(0, 15):
            self.model2.setItem(number, 0, QStandardItem('S' + str(number + 18)))
        self.model2.setItem(0, 1, QStandardItem('初始化速度(10~40000)'))
        self.model2.setItem(1, 1, QStandardItem('第二加速度(100~40000)'))
        self.model2.setItem(2, 1, QStandardItem('倒车加速度(100~40000)'))
        self.model2.setItem(3, 1, QStandardItem('减速度(10~40000)'))
        self.model2.setItem(4, 1, QStandardItem('刹车减速度(100~40000)'))
        self.model2.setItem(5, 1, QStandardItem('速度KP(100~40000)'))
        self.model2.setItem(6, 1, QStandardItem('速度KI(0~20000)'))
        self.model2.setItem(7, 1, QStandardItem('转折频率(0~电机额定频率)'))
        self.model2.setItem(8, 1, QStandardItem('转差频率限定(1.0~电机额定频率)'))
        self.model2.setItem(9, 1, QStandardItem('测速滤波系数(0~7)'))
        self.model2.setItem(10, 1, QStandardItem('启动位置自学习(0~7)'))
        self.model2.setItem(11, 1, QStandardItem('输出电流限定(0~600.0A)'))
        self.model2.setItem(12, 1, QStandardItem('定子电阻(0~32767)mΩ'))
        self.model2.setItem(13, 1, QStandardItem('保留1(0~32767)'))
        self.model2.setItem(14, 1, QStandardItem('保留2(0~32767)'))
        for number in range(0, 16):
            self.model3.setItem(number, 0, QStandardItem('S' + str(number + 33)))
        self.model3.setItem(0, 1, QStandardItem('转矩KP(100~40000)'))
        self.model3.setItem(1, 1, QStandardItem('转矩KI(0~20000)'))
        self.model3.setItem(2, 1, QStandardItem('激磁KP(100~40000)'))
        self.model3.setItem(3, 1, QStandardItem('激磁KI(0~20000)'))
        self.model3.setItem(4, 1, QStandardItem('驱动转矩限定(0~400%)'))
        self.model3.setItem(5, 1, QStandardItem('制动转矩限定(0~400%)'))
        self.model3.setItem(6, 1, QStandardItem('电压校正系数(90~110%)'))
        self.model3.setItem(7, 1, QStandardItem('电流矫正系数(50~200%)'))
        self.model3.setItem(8, 1, QStandardItem('欠压点设定(0~1000V)'))
        self.model3.setItem(9, 1, QStandardItem('过压点设定(0~1000V)'))
        self.model3.setItem(10, 1, QStandardItem('厂家参数1(0~65535)'))
        self.model3.setItem(11, 1, QStandardItem('控制模式选择(0~7)'))
        self.model3.setItem(12, 1, QStandardItem('高速转矩设定(0~400%)'))
        self.model3.setItem(13, 1, QStandardItem('保留1(0~32767)'))
        self.model3.setItem(14, 1, QStandardItem('保留2(0~32767)'))
        self.model3.setItem(15, 1, QStandardItem('保留3(0~32767)'))
        for number in range(0, 9):
            self.model4.setItem(number, 0, QStandardItem('S' + str(number + 49)))
        self.model4.setItem(0, 1, QStandardItem('输出电流'))
        self.model4.setItem(1, 1, QStandardItem('电机转速'))
        self.model4.setItem(2, 1, QStandardItem('控制器温度'))
        self.model4.setItem(3, 1, QStandardItem('电机温度'))
        self.model4.setItem(4, 1, QStandardItem('电池组电压'))
        self.model4.setItem(5, 1, QStandardItem('故障信息'))
        self.model4.setItem(6, 1, QStandardItem('最后一次故障'))
        self.model4.setItem(7, 1, QStandardItem('保留2(0~32767)'))
        self.model4.setItem(8, 1, QStandardItem('保留3(0~32767)'))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "捷科斯控制调试软件"))
        self.label_4.setText(_translate("MainWindow", "读取成功"))
        self.toolButton.setText(_translate("MainWindow", "连接"))
        self.toolButton_2.setText(_translate("MainWindow", "断开"))
        self.toolButton_3.setText(_translate("MainWindow", "配置"))
        self.toolButton_4.setText(_translate("MainWindow", "修改"))
        self.toolButton_5.setText(_translate("MainWindow", "关于"))
        self.toolButton_6.setText(_translate("MainWindow", "ENG"))


